version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  build_and_push_image:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          account-url: ${AWS_ECR_ACCOUNT_URL}
          region: us-east-1
          repo: nextjs-on-aws
          tag: latest
          #context: myContext
          #create-repo: true
          #profile-name: myProfileName

jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
