version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  build_push_and_deploy_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: nextjs-on-aws
          tag: latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: 'nextjs-on-aws-service'
          cluster-name: 'nextjs-on-aws-cluster'
          container-image-name-updates: 'container=nextjs-on-aws-service,tag=latest'

