version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: nextjs-on-aws
          tag: latest
          #context: myContext
          #create-repo: true
          #profile-name: myProfileName
