version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-ecs: circleci/aws-ecs@0.0.6

workflows:
  build_push_and_deploy_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: nextjs-on-aws
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: 'nextjs-td'
          service-name: 'my-service'
          cluster-name: 'my-cluster'
          container-image-name-updates: 'container=nextjs-container,tag=${CIRCLE_SHA1}'

